// ─── Types ────────────────────────────────────────────────────────────────────

export interface Scheme {
  slug: string;
  title: string;
  shortTitle: string;
  description: string;
  benefit: string;
  category: "agriculture" | "education" | "health" | "housing" | "employment" | "women" | "finance" | "infrastructure";
  eligibility: string[];
  documents: string[];
  applyLink: string;
  launchYear: number;
  keywords: string[];
  faqs: { q: string; a: string }[];
  isPopular?: boolean;
}

export interface State {
  slug: string;
  name: string;
  hindiName: string;
  capital: string;
  population: string;
  totalSchemes: number;
  icon: string;
}

// ─── States ───────────────────────────────────────────────────────────────────

export const states: State[] = [
  { slug: "maharashtra", name: "Maharashtra", hindiName: "महाराष्ट्र", capital: "Mumbai", population: "12.4 Cr", totalSchemes: 48, icon: "🏙️" },
  { slug: "uttar-pradesh", name: "Uttar Pradesh", hindiName: "उत्तर प्रदेश", capital: "Lucknow", population: "24 Cr", totalSchemes: 62, icon: "🕌" },
  { slug: "rajasthan", name: "Rajasthan", hindiName: "राजस्थान", capital: "Jaipur", population: "8.1 Cr", totalSchemes: 41, icon: "🏜️" },
  { slug: "madhya-pradesh", name: "Madhya Pradesh", hindiName: "मध्य प्रदेश", capital: "Bhopal", population: "8.5 Cr", totalSchemes: 44, icon: "🌲" },
  { slug: "bihar", name: "Bihar", hindiName: "बिहार", capital: "Patna", population: "12.8 Cr", totalSchemes: 39, icon: "🛕" },
  { slug: "gujarat", name: "Gujarat", hindiName: "गुजरात", capital: "Gandhinagar", population: "7.1 Cr", totalSchemes: 45, icon: "⚓" },
  { slug: "west-bengal", name: "West Bengal", hindiName: "पश्चिम बंगाल", capital: "Kolkata", population: "10.1 Cr", totalSchemes: 36, icon: "🐯" },
  { slug: "karnataka", name: "Karnataka", hindiName: "कर्नाटक", capital: "Bengaluru", population: "6.7 Cr", totalSchemes: 42, icon: "🌺" },
  { slug: "tamil-nadu", name: "Tamil Nadu", hindiName: "तमिल नाडु", capital: "Chennai", population: "8.2 Cr", totalSchemes: 40, icon: "🏛️" },
  { slug: "andhra-pradesh", name: "Andhra Pradesh", hindiName: "आंध्र प्रदेश", capital: "Amaravati", population: "5.4 Cr", totalSchemes: 35, icon: "🌊" },
  { slug: "telangana", name: "Telangana", hindiName: "तेलंगाना", capital: "Hyderabad", population: "3.8 Cr", totalSchemes: 33, icon: "💎" },
  { slug: "kerala", name: "Kerala", hindiName: "केरल", capital: "Thiruvananthapuram", population: "3.5 Cr", totalSchemes: 38, icon: "🌴" },
  { slug: "punjab", name: "Punjab", hindiName: "पंजाब", capital: "Chandigarh", population: "3.1 Cr", totalSchemes: 31, icon: "🌾" },
  { slug: "haryana", name: "Haryana", hindiName: "हरियाणा", capital: "Chandigarh", population: "2.9 Cr", totalSchemes: 34, icon: "🐄" },
  { slug: "jharkhand", name: "Jharkhand", hindiName: "झारखंड", capital: "Ranchi", population: "3.8 Cr", totalSchemes: 29, icon: "⛏️" },
  { slug: "chhattisgarh", name: "Chhattisgarh", hindiName: "छत्तीसगढ़", capital: "Raipur", population: "2.9 Cr", totalSchemes: 27, icon: "🌿" },
  { slug: "odisha", name: "Odisha", hindiName: "ओडिशा", capital: "Bhubaneswar", population: "4.7 Cr", totalSchemes: 32, icon: "🎨" },
  { slug: "assam", name: "Assam", hindiName: "असम", capital: "Dispur", population: "3.5 Cr", totalSchemes: 28, icon: "🍵" },
  { slug: "himachal-pradesh", name: "Himachal Pradesh", hindiName: "हिमाचल प्रदेश", capital: "Shimla", population: "73 Lakh", totalSchemes: 24, icon: "🏔️" },
  { slug: "uttarakhand", name: "Uttarakhand", hindiName: "उत्तराखंड", capital: "Dehradun", population: "1.1 Cr", totalSchemes: 26, icon: "🏞️" },
  { slug: "delhi", name: "Delhi", hindiName: "दिल्ली", capital: "New Delhi", population: "2.0 Cr", totalSchemes: 30, icon: "🏛️" },
  { slug: "goa", name: "Goa", hindiName: "गोवा", capital: "Panaji", population: "15 Lakh", totalSchemes: 18, icon: "🏖️" },
];

// ─── Central Government Schemes ───────────────────────────────────────────────

export const centralSchemes: Scheme[] = [
  {
    slug: "pm-vishwakarma-yojana",
    title: "PM Vishwakarma Yojana 2025",
    shortTitle: "PM Vishwakarma",
    description: "PM Vishwakarma Yojana provides financial assistance, skill training, and recognition to traditional artisans and craftspeople across India covering 18 trades.",
    benefit: "₹3 Lakh loan at 5% interest + ₹15,000 toolkit + free skill training",
    category: "employment",
    eligibility: [
      "Traditional artisan or craftsperson",
      "Must belong to one of 18 eligible trades",
      "Age 18 years or above",
      "Self-employed (not salaried)",
      "Not enrolled in any similar central/state scheme",
    ],
    documents: ["Aadhaar Card", "Mobile number linked to Aadhaar", "Bank account details", "Caste certificate (if applicable)", "Proof of trade/craft"],
    applyLink: "https://pmvishwakarma.gov.in",
    launchYear: 2023,
    keywords: ["pm vishwakarma yojana registration", "vishwakarma yojana login", "pm vishwakarma documents", "vishwakarma yojana eligibility", "vishwakarma yojana loan"],
    isPopular: true,
    faqs: [
      { q: "What is PM Vishwakarma Yojana?", a: "PM Vishwakarma Yojana is a central government scheme launched on September 17, 2023 to support traditional artisans and craftspeople with skill training, toolkit support, and collateral-free loans." },
      { q: "Who is eligible for PM Vishwakarma Yojana?", a: "Any traditional artisan or craftsperson who works with hands and tools, belongs to one of the 18 eligible trades, is 18+ years old, and is self-employed can apply." },
      { q: "What is the loan amount under PM Vishwakarma Yojana?", a: "Eligible artisans can get up to ₹1 lakh in the first tranche and ₹2 lakh in the second tranche (total ₹3 lakh) at a concessional interest rate of 5% per annum." },
      { q: "How to apply for PM Vishwakarma Yojana online?", a: "Visit pmvishwakarma.gov.in, click on 'Apply Now', register with your Aadhaar-linked mobile number, fill in the application form, and submit the required documents." },
      { q: "What are the 18 trades covered?", a: "The 18 trades include Carpenter, Boat Maker, Armourer, Blacksmith, Hammer & Tool Kit Maker, Locksmith, Goldsmith, Potter, Sculptor, Cobbler, Mason, Basket/Mat/Broom Maker, Doll & Toy Maker, Barber, Garland Maker, Washerman, Tailor, and Fishing Net Maker." },
      { q: "Is PM Vishwakarma Yojana only for certain castes?", a: "No, the scheme is open to artisans from all communities who practice one of the 18 eligible traditional crafts or trades." },
      { q: "What is the toolkit e-voucher benefit?", a: "Enrolled beneficiaries receive a ₹15,000 e-voucher to purchase tools and equipment required for their trade from registered vendors on the portal." },
      { q: "Can women apply for PM Vishwakarma Yojana?", a: "Yes, women artisans and craftspeople are fully eligible to apply and are encouraged to participate." },
    ],
  },
  {
    slug: "pm-awas-yojana",
    title: "PM Awas Yojana 2025 — Pradhan Mantri Awas Yojana",
    shortTitle: "PM Awas Yojana",
    description: "Pradhan Mantri Awas Yojana provides financial assistance for construction of pucca houses to homeless and kutcha house-dwelling families in rural and urban areas.",
    benefit: "₹1.20 lakh (rural) to ₹2.67 lakh (urban) housing subsidy",
    category: "housing",
    eligibility: ["BPL family", "No pucca house", "Not availed housing benefit before", "Annual income under ₹3 lakh (urban)"],
    documents: ["Aadhaar Card", "BPL Certificate", "Bank Passbook", "Income Certificate", "Land ownership proof"],
    applyLink: "https://pmayg.nic.in",
    launchYear: 2016,
    keywords: ["pm awas yojana list 2025", "pradhan mantri awas yojana apply", "pmay registration", "awas yojana gramin"],
    isPopular: true,
    faqs: [
      { q: "What is PM Awas Yojana?", a: "PM Awas Yojana is a flagship housing scheme providing financial assistance to economically weaker sections to construct or purchase a pucca house." },
      { q: "How much subsidy is given under PMAY?", a: "Under PMAY-Gramin, ₹1.20 lakh is given in plain areas and ₹1.30 lakh in hilly/difficult areas. Under PMAY-Urban, interest subsidy up to ₹2.67 lakh is provided." },
      { q: "How to check PM Awas Yojana list?", a: "Visit pmayg.nic.in, click on 'Awaassoft', then 'Report', and select 'Beneficiary details for verification' to check your name in the list." },
      { q: "Can I apply for PM Awas Yojana online?", a: "Yes, you can apply through the official PMAY portal at pmaymis.gov.in for urban areas or through your local Gram Panchayat for rural areas." },
    ],
  },
  {
    slug: "pm-kisan-samman-nidhi",
    title: "PM Kisan Samman Nidhi Yojana 2025",
    shortTitle: "PM Kisan",
    description: "PM-KISAN provides ₹6,000 per year direct income support to all land-holding farmer families across India in three equal instalments of ₹2,000.",
    benefit: "₹6,000/year directly to bank account in 3 instalments",
    category: "agriculture",
    eligibility: ["Land-owning farmer family", "Valid Aadhaar", "Bank account linked", "Not income tax payee"],
    documents: ["Aadhaar Card", "Land records / Khasra-Khatauni", "Bank Passbook", "Mobile number"],
    applyLink: "https://pmkisan.gov.in",
    launchYear: 2019,
    keywords: ["pm kisan status", "pm kisan 18th installment", "pm kisan beneficiary list", "pm kisan registration"],
    isPopular: true,
    faqs: [
      { q: "When is the next PM Kisan installment?", a: "PM Kisan instalments are released 3 times a year — April-July, August-November, and December-March. The exact date is announced by the government." },
      { q: "How to check PM Kisan status?", a: "Go to pmkisan.gov.in, click 'Beneficiary Status', enter your Aadhaar number or mobile number to check your payment status." },
    ],
  },
  {
    slug: "ayushman-bharat-yojana",
    title: "Ayushman Bharat PM-JAY Yojana 2025",
    shortTitle: "Ayushman Bharat",
    description: "Ayushman Bharat provides free health insurance coverage of ₹5 lakh per family per year for secondary and tertiary hospitalisation to economically vulnerable families.",
    benefit: "₹5 lakh free health insurance per family per year",
    category: "health",
    eligibility: ["SECC database listed family", "No private health insurance", "Any age group covered"],
    documents: ["Aadhaar Card", "Ration Card", "SECC/BPL Certificate"],
    applyLink: "https://pmjay.gov.in",
    launchYear: 2018,
    keywords: ["ayushman bharat card download", "pm jan arogya yojana eligibility", "ayushman card apply online", "pmjay hospital list"],
    isPopular: true,
    faqs: [
      { q: "Who is eligible for Ayushman Bharat?", a: "Families listed in the SECC 2011 database, including rural families with deprived categories and urban workers in 11 occupational categories." },
      { q: "How to download Ayushman Card?", a: "Visit beneficiary.nha.gov.in, enter your mobile number, verify OTP, and download your Ayushman Bharat health card." },
    ],
  },
  {
    slug: "pm-ujjwala-yojana",
    title: "PM Ujjwala Yojana 2.0 — Free LPG Connection",
    shortTitle: "PM Ujjwala",
    description: "Pradhan Mantri Ujjwala Yojana provides free LPG gas connections to women from below poverty line households to replace unhealthy cooking fuel usage.",
    benefit: "Free LPG connection + ₹1,600 financial assistance",
    category: "women",
    eligibility: ["Women 18+ years", "BPL household", "No existing LPG connection", "Not availed PMUY before"],
    documents: ["Aadhaar Card", "BPL Ration Card", "Bank Passbook", "Passport photo"],
    applyLink: "https://pmuy.gov.in",
    launchYear: 2016,
    keywords: ["pm ujjwala yojana apply", "ujjwala yojana 2.0 registration", "free lpg connection apply", "pmuy eligibility"],
    isPopular: true,
    faqs: [
      { q: "What is PM Ujjwala Yojana 2.0?", a: "PMUY 2.0 extends the scheme to more beneficiaries including migrants and adds portability for refills anywhere in India." },
      { q: "How to apply for PM Ujjwala Yojana?", a: "Visit the nearest LPG distributor (HP, Bharatgas, or Indane) or apply online at pmuy.gov.in with your Aadhaar and BPL certificate." },
    ],
  },
  {
    slug: "pm-yasasvi-scholarship",
    title: "PM YASASVI Scholarship Scheme 2025",
    shortTitle: "PM YASASVI",
    description: "PM Young Achievers Scholarship Award Scheme for Vibrant India provides scholarships to OBC, EBC, and DNT students for education in Classes 9-12.",
    benefit: "₹75,000/year for residential school students, ₹25,000/year for day scholars",
    category: "education",
    eligibility: ["OBC/EBC/DNT category student", "Class 9 to 12", "Annual family income ≤ ₹2.5 lakh", "Selected through NTA exam"],
    documents: ["Caste Certificate", "Income Certificate", "School enrollment proof", "Aadhaar Card"],
    applyLink: "https://yet.nta.ac.in",
    launchYear: 2023,
    keywords: ["pm yasasvi scholarship 2025 apply", "yasasvi scholarship eligibility", "yasasvi exam date 2025", "pm yasasvi obc scholarship"],
    isPopular: false,
    faqs: [
      { q: "What is PM YASASVI Scholarship?", a: "It is a scholarship for OBC, EBC, and DNT students studying in Classes 9-12, selected through the YASASVI Entrance Test conducted by NTA." },
      { q: "How much scholarship amount is given?", a: "Students in residential schools/hostels get ₹75,000/year and day scholars in top-class schools get ₹25,000/year." },
    ],
  },
  {
    slug: "pm-svanidhi",
    title: "PM SVANidhi — Street Vendor Loan Scheme 2025",
    shortTitle: "PM SVANidhi",
    description: "PM Street Vendor's AtmaNirbhar Nidhi provides collateral-free working capital loans to street vendors to resume their livelihoods post-COVID disruption.",
    benefit: "Loans of ₹10,000 → ₹20,000 → ₹50,000 + digital cashback rewards",
    category: "finance",
    eligibility: ["Street vendor in any city/town", "Certificate of Vending issued", "Age 18+"],
    documents: ["Aadhaar Card", "Vendor Certificate / Letter of Recommendation", "Bank passbook", "Mobile number"],
    applyLink: "https://pmsvanidhi.mohua.gov.in",
    launchYear: 2020,
    keywords: ["pm svanidhi loan apply", "street vendor loan scheme", "svanidhi yojana registration", "pm svanidhi 50000 loan"],
    isPopular: false,
    faqs: [
      { q: "What loans are available under PM SVANidhi?", a: "Vendors can get ₹10,000 initially, then ₹20,000, and finally ₹50,000 as they repay each loan — a step-up lending model." },
      { q: "Who can apply for PM SVANidhi?", a: "Any street vendor who is vending in urban areas, has a Certificate of Vending, or has a Letter of Recommendation from a Town Vending Committee." },
    ],
  },
  {
    slug: "pm-suraksha-bima-yojana",
    title: "PM Suraksha Bima Yojana — ₹2 Lakh Accident Insurance",
    shortTitle: "PM Suraksha Bima",
    description: "PMSBY provides accidental death and disability insurance cover of ₹2 lakh for just ₹20 per year, renewable annually through bank auto-debit.",
    benefit: "₹2 lakh accident cover for only ₹20/year",
    category: "finance",
    eligibility: ["Age 18–70 years", "Active bank account with auto-debit facility", "Aadhaar linked to bank"],
    documents: ["Aadhaar Card", "Bank account details"],
    applyLink: "https://jansuraksha.gov.in",
    launchYear: 2015,
    keywords: ["pmsby enrollment", "suraksha bima yojana claim", "pm suraksha bima ₹20", "accident insurance scheme india"],
    isPopular: false,
    faqs: [
      { q: "What is covered under PMSBY?", a: "Death or total permanent disability due to accident gets ₹2 lakh. Partial permanent disability gets ₹1 lakh." },
      { q: "How to enroll in PM Suraksha Bima Yojana?", a: "Contact your bank branch or enroll through internet banking/mobile app to activate this insurance with just ₹20/year deducted automatically." },
    ],
  },
  {
    slug: "pm-mudra-yojana",
    title: "PM Mudra Yojana — Business Loan up to ₹20 Lakh",
    shortTitle: "PM Mudra Yojana",
    description: "Pradhan Mantri Mudra Yojana offers collateral-free business loans to micro and small enterprises under three categories — Shishu (₹50K), Kishore (₹5L), and Tarun (₹20L).",
    benefit: "Collateral-free loan ₹50,000 to ₹20 lakh at low interest",
    category: "finance",
    eligibility: ["Non-corporate, non-farm small business", "Micro enterprise or self-employed individual", "Existing business or new startup", "No default on previous loans"],
    documents: ["Aadhaar Card", "PAN Card", "Business proof / registration", "Bank statement (6 months)", "Passport photo", "Quotation for equipment (if applicable)"],
    applyLink: "https://mudra.org.in",
    launchYear: 2015,
    keywords: ["mudra loan apply online 2025", "pm mudra yojana eligibility", "mudra loan ₹10 lakh", "kishore mudra loan", "tarun mudra loan"],
    isPopular: true,
    faqs: [
      { q: "What are the three categories under PM Mudra Yojana?", a: "Shishu: up to ₹50,000 for startups; Kishore: ₹50,001 to ₹5 lakh for growing businesses; Tarun: ₹5 lakh to ₹20 lakh for established businesses." },
      { q: "Which banks offer Mudra loans?", a: "All PSU banks, private banks, RRBs, MFIs, and NBFCs are registered Mudra lenders. Apply at any branch or through udyamimitra.in online portal." },
      { q: "Is collateral required for Mudra loan?", a: "No collateral or guarantor is required for Mudra loans under all three categories." },
      { q: "How long does Mudra loan approval take?", a: "Typically 7–14 working days after document submission, depending on the bank." },
    ],
  },
  {
    slug: "sukanya-samriddhi-yojana",
    title: "Sukanya Samriddhi Yojana 2025 — Girl Child Savings Scheme",
    shortTitle: "Sukanya Samriddhi",
    description: "Sukanya Samriddhi Yojana is a government-backed savings scheme for girl children offering one of the highest fixed interest rates (8.2% p.a.) with full tax exemption under Section 80C.",
    benefit: "8.2% p.a. interest + full tax exemption (80C) for girl education & marriage",
    category: "women",
    eligibility: ["Girl child below 10 years", "Indian resident", "Only 2 accounts per family (one per girl child)"],
    documents: ["Girl child birth certificate", "Parent/guardian Aadhaar Card", "Parent/guardian PAN Card", "Address proof"],
    applyLink: "https://www.indiapost.gov.in",
    launchYear: 2015,
    keywords: ["sukanya samriddhi yojana interest rate 2025", "sukanya samriddhi account open", "ssy calculator", "sukanya samriddhi minimum amount"],
    isPopular: true,
    faqs: [
      { q: "What is the current interest rate for Sukanya Samriddhi Yojana?", a: "The current interest rate is 8.2% per annum (Q1 FY 2025-26), compounded annually. It is one of the highest government-guaranteed rates." },
      { q: "Where can I open a Sukanya Samriddhi account?", a: "You can open an SSY account at any post office or authorized banks including SBI, PNB, Bank of Baroda, and most major banks." },
      { q: "What is the minimum deposit for SSY?", a: "The minimum deposit is Rs.250 per year and the maximum is Rs.1.5 lakh per year." },
      { q: "When can I withdraw from SSY?", a: "50% partial withdrawal is allowed after the girl turns 18 for education. Full withdrawal is allowed on maturity (21 years from account opening) or marriage after 18 years." },
    ],
  },
  {
    slug: "atal-pension-yojana",
    title: "Atal Pension Yojana — Guaranteed Pension for Workers",
    shortTitle: "Atal Pension Yojana",
    description: "Atal Pension Yojana provides a guaranteed monthly pension of Rs.1,000 to Rs.5,000 after age 60 to unorganized sector workers based on their contribution amount and age at enrollment.",
    benefit: "Rs.1,000 to Rs.5,000 guaranteed monthly pension after age 60",
    category: "finance",
    eligibility: ["Age 18 to 40 years", "Indian citizen", "Active bank/post office savings account", "Not an income tax payer (after 2022 amendment)"],
    documents: ["Aadhaar Card", "Mobile number linked to bank", "Bank savings account"],
    applyLink: "https://npscra.nsdl.co.in",
    launchYear: 2015,
    keywords: ["atal pension yojana registration", "apy pension amount", "atal pension yojana chart", "apy contribution calculator"],
    isPopular: false,
    faqs: [
      { q: "How much pension will I get under APY?", a: "Depending on the pension plan (Rs.1K to Rs.5K/month) you choose and your age at enrollment, your monthly contribution varies from Rs.42 to Rs.1,454." },
      { q: "Can I exit APY before 60 years?", a: "Voluntary exit before 60 is allowed but the subscriber only gets their own contribution plus interest, minus account maintenance charges." },
      { q: "What happens if I miss APY contributions?", a: "A penalty of Rs.1 per month per Rs.100 contribution is charged for defaults. Account is frozen after 6 months of non-payment and closed after 24 months." },
    ],
  },
  {
    slug: "pm-jeevan-jyoti-bima-yojana",
    title: "PM Jeevan Jyoti Bima Yojana — Rs.2 Lakh Life Insurance",
    shortTitle: "PM Jeevan Jyoti",
    description: "PMJJBY is a renewable term life insurance scheme offering a Rs.2 lakh death cover for just Rs.436 per year, automatically debited from the subscriber bank account.",
    benefit: "Rs.2 lakh life insurance cover for only Rs.436/year",
    category: "finance",
    eligibility: ["Age 18 to 50 years", "Active savings bank or post office account", "Consent for auto-debit"],
    documents: ["Aadhaar Card", "Bank account details"],
    applyLink: "https://jansuraksha.gov.in",
    launchYear: 2015,
    keywords: ["pmjjby enrollment 2025", "jeevan jyoti bima claim process", "pm jeevan jyoti bima yojana", "life insurance Rs.2 lakh scheme"],
    isPopular: false,
    faqs: [
      { q: "What does PMJJBY cover?", a: "It covers death due to any cause. Rs.2 lakh is paid to the nominee in case of the policyholder death during the policy year." },
      { q: "How do I enroll in PMJJBY?", a: "Visit your bank branch or enroll via net banking or bank app. The premium of Rs.436/year is auto-debited between 25 May and 31 May each year." },
    ],
  },
  {
    slug: "pm-fasal-bima-yojana",
    title: "PM Fasal Bima Yojana — Crop Insurance Scheme 2025",
    shortTitle: "PM Fasal Bima",
    description: "Pradhan Mantri Fasal Bima Yojana provides comprehensive financial support to farmers who suffer crop loss due to natural calamities, pests, or diseases at very low premium rates.",
    benefit: "Crop loss compensation with premium as low as 1.5% to 5% of sum insured",
    category: "agriculture",
    eligibility: ["All farmers growing notified crops", "Both loanee and non-loanee farmers", "Sharecroppers and tenant farmers also eligible"],
    documents: ["Aadhaar Card", "Land records (Khasra/Khatauni)", "Bank passbook", "Sowing certificate"],
    applyLink: "https://pmfby.gov.in",
    launchYear: 2016,
    keywords: ["pm fasal bima yojana apply", "pmfby status check", "fasal bima claim 2025", "crop insurance india"],
    isPopular: false,
    faqs: [
      { q: "What crops are covered under PM Fasal Bima Yojana?", a: "Food crops (cereals, millets, pulses), oilseeds, and annual commercial/horticultural crops that are notified by respective state governments." },
      { q: "What is the premium rate for PMFBY?", a: "Kharif crops: 2% of sum insured; Rabi crops: 1.5%; annual commercial/horticultural crops: 5%. The rest of the premium is borne by the government." },
      { q: "How to claim crop insurance under PMFBY?", a: "Report crop loss within 72 hours through the PMFBY app or portal, or by calling the insurance company helpline. Compensation is transferred to the bank after survey." },
    ],
  },
  {
    slug: "kisan-credit-card",
    title: "Kisan Credit Card (KCC) Scheme 2025",
    shortTitle: "Kisan Credit Card",
    description: "Kisan Credit Card provides farmers with flexible and affordable short-term credit for cultivation expenses, post-harvest needs, and allied activities at interest rates as low as 4% per annum.",
    benefit: "Crop loan at 4% interest p.a. up to Rs.3 lakh; credit limit based on land holding",
    category: "agriculture",
    eligibility: ["All farmers including individual, joint cultivators, and self-help groups", "Tenant farmers and oral lessees also eligible", "Fishermen and animal husbandry farmers also covered"],
    documents: ["Aadhaar Card", "Land records (7/12 or Khasra)", "PAN Card", "Passport photo", "Crop details"],
    applyLink: "https://www.nabard.org",
    launchYear: 1998,
    keywords: ["kisan credit card apply 2025", "kcc interest rate", "kisan credit card limit", "kcc online apply", "kisan credit card benefits"],
    isPopular: true,
    faqs: [
      { q: "What is the interest rate on Kisan Credit Card?", a: "The basic interest rate is 9%, but with government interest subvention of 2% and prompt repayment incentive of 3%, the effective rate is as low as 4% per annum." },
      { q: "What is the credit limit on KCC?", a: "The credit limit depends on the land area, cropping pattern, and scale of finance. For loans up to Rs.3 lakh, interest subvention applies." },
      { q: "Can fishermen get Kisan Credit Card?", a: "Yes, the scheme was extended to fishermen and fish farmers in 2020 to cover fishing vessel and equipment purchase and working capital needs." },
    ],
  },
  {
    slug: "beti-bachao-beti-padhao",
    title: "Beti Bachao Beti Padhao Yojana 2025",
    shortTitle: "Beti Bachao Beti Padhao",
    description: "Beti Bachao Beti Padhao is a national initiative to address the declining child sex ratio and promote the welfare, education, and empowerment of the girl child across India.",
    benefit: "Financial incentives, free education, scholarships, and health support for girl child",
    category: "women",
    eligibility: ["All girl children across India", "Special focus on districts with low sex ratio", "Government schools under Udaan and Sukanya schemes"],
    documents: ["Girl child birth certificate", "Aadhaar Card", "School enrollment proof"],
    applyLink: "https://wcd.nic.in",
    launchYear: 2015,
    keywords: ["beti bachao beti padhao yojana apply", "bbbp scheme benefits", "girl child scheme india", "beti bachao yojana documents"],
    isPopular: false,
    faqs: [
      { q: "What are the key benefits of Beti Bachao Beti Padhao?", a: "Benefits include financial incentives for families with girl children, free education support, improved healthcare for girls, and community awareness programs to prevent female foeticide." },
      { q: "Which ministry runs Beti Bachao Beti Padhao?", a: "It is a joint initiative of Ministry of Women and Child Development, Ministry of Health and Family Welfare, and Ministry of Education." },
    ],
  },
  {
    slug: "stand-up-india",
    title: "Stand Up India Scheme 2025 — SC/ST & Women Entrepreneurs",
    shortTitle: "Stand Up India",
    description: "Stand Up India facilitates bank loans between Rs.10 lakh and Rs.1 crore to at least one SC or ST borrower and one woman borrower per bank branch for setting up greenfield enterprises.",
    benefit: "Bank loan Rs.10 lakh to Rs.1 crore for SC/ST and women entrepreneurs",
    category: "employment",
    eligibility: ["SC, ST, or woman entrepreneur", "Age 18 or above", "Setting up a new greenfield enterprise", "Not defaulter with any bank or financial institution"],
    documents: ["Aadhaar Card", "PAN Card", "Caste certificate for SC/ST", "Business plan or project report", "Bank account details"],
    applyLink: "https://www.standupmitra.in",
    launchYear: 2016,
    keywords: ["stand up india loan apply", "stand up india eligibility", "sc st entrepreneur loan", "women entrepreneur loan india"],
    isPopular: false,
    faqs: [
      { q: "What is a greenfield enterprise under Stand Up India?", a: "A greenfield enterprise means a new business being set up for the first time in manufacturing, services, or trading sectors." },
      { q: "How to apply for Stand Up India loan?", a: "Apply at any bank branch or online at standupmitra.in. The portal connects applicants with banks, handholding agencies, and provides training resources." },
    ],
  },
  {
    slug: "pmegp",
    title: "PMEGP — PM Employment Generation Programme 2025",
    shortTitle: "PMEGP",
    description: "Prime Minister Employment Generation Programme provides government subsidy of 15 to 35% on project costs to set up micro-enterprises, creating self-employment for unemployed youth.",
    benefit: "15 to 35% government subsidy on project cost (up to Rs.50 lakh manufacturing, Rs.20 lakh service)",
    category: "employment",
    eligibility: ["Age 18 or above", "Minimum 8th standard pass for projects above Rs.10 lakh", "No income limit for General category", "One individual per family eligible"],
    documents: ["Aadhaar Card", "PAN Card", "Educational qualification certificate", "Project report", "Passport photo"],
    applyLink: "https://www.kviconline.gov.in/pmegpeportal",
    launchYear: 2008,
    keywords: ["pmegp loan apply 2025", "pmegp subsidy rate", "pmegp eligibility 2025", "pm employment generation programme apply"],
    isPopular: false,
    faqs: [
      { q: "What is the maximum project cost under PMEGP?", a: "For manufacturing sector: Rs.50 lakh. For business/service sector: Rs.20 lakh. The government subsidy is 15 to 35% depending on category and location." },
      { q: "Who implements PMEGP?", a: "PMEGP is implemented by Khadi and Village Industries Commission (KVIC) at the national level, through State KVICs, DICs, and KVIBs at the state and district levels." },
    ],
  },
  {
    slug: "jal-jeevan-mission",
    title: "Jal Jeevan Mission — Har Ghar Jal Yojana 2025",
    shortTitle: "Jal Jeevan Mission",
    description: "Jal Jeevan Mission aims to provide safe and adequate drinking water through individual household tap connections to all rural households in India with functional household tap connection.",
    benefit: "Free piped tap water connection to every rural household",
    category: "infrastructure",
    eligibility: ["All rural households without existing piped water connection", "Focus on SC/ST and economically weaker households"],
    documents: ["Aadhaar Card", "Proof of residence", "No-objection from Gram Panchayat"],
    applyLink: "https://jaljeevanmission.gov.in",
    launchYear: 2019,
    keywords: ["jal jeevan mission tap connection", "har ghar jal yojana apply", "jjm rural water supply", "jal jeevan mission status"],
    isPopular: false,
    faqs: [
      { q: "What is the Jal Jeevan Mission target?", a: "To provide Functional Household Tap Connection (FHTC) to every rural household in India with minimum 55 litres per person per day of potable water supply." },
      { q: "Is there any cost to the household for tap connection?", a: "The central and state governments bear the infrastructure cost. Households may pay a nominal monthly water tariff as decided by the Gram Panchayat." },
    ],
  },
  {
    slug: "pm-poshan-scheme",
    title: "PM POSHAN — Free Mid-Day Meal Scheme 2025",
    shortTitle: "PM POSHAN",
    description: "PM Poshan Shakti Nirman (formerly Mid-Day Meal Scheme) provides free hot cooked meals to students in government and government-aided schools to improve nutrition and boost school attendance.",
    benefit: "Free nutritious cooked meal daily for all government school students",
    category: "education",
    eligibility: ["Students in Class 1 to 8 in government or aided schools", "Children in Bal Vatika pre-primary also covered"],
    documents: ["School enrollment or admission record"],
    applyLink: "https://pmposhan.education.gov.in",
    launchYear: 1995,
    keywords: ["pm poshan scheme 2025", "mid day meal scheme india", "pm poshan eligibility", "free lunch school scheme"],
    isPopular: false,
    faqs: [
      { q: "Which students are covered under PM POSHAN?", a: "All students studying in Classes 1 to 8 in government, government-aided schools, and Ashram Shalas. Bal Vatika pre-primary students are also included since 2021." },
      { q: "What nutrition standards apply to the mid-day meals?", a: "Meals must provide 450 Kcal energy and 12g protein for primary students (Class 1 to 5), and 700 Kcal and 20g protein for upper primary students (Class 6 to 8)." },
    ],
  },
  {
    slug: "national-scholarship-portal",
    title: "National Scholarship Portal (NSP) — Central Scholarships 2025",
    shortTitle: "NSP Scholarships",
    description: "The National Scholarship Portal is a one-stop platform for students to apply for all central government scholarship schemes including pre-matric, post-matric, and merit-cum-means scholarships for SC, ST, OBC, and minority students.",
    benefit: "Scholarships from Rs.1,000 to Rs.20,000/year depending on category and level",
    category: "education",
    eligibility: ["SC/ST/OBC/Minority students", "Income limit varies by scheme typically Rs.1 to 2.5 lakh", "Pre-matric: Class 9 to 10; Post-matric: Class 11 onwards"],
    documents: ["Aadhaar Card", "Caste/community certificate", "Income certificate", "Bank passbook", "Previous year mark sheet", "School/college enrollment proof"],
    applyLink: "https://scholarships.gov.in",
    launchYear: 2015,
    keywords: ["national scholarship portal apply 2025", "nsp scholarship status", "pre matric scholarship", "post matric scholarship apply", "nsp login"],
    isPopular: true,
    faqs: [
      { q: "What scholarships are available on the National Scholarship Portal?", a: "Over 50 scholarship schemes from central ministries covering pre-matric, post-matric, and merit-cum-means scholarships for SC, ST, OBC, EBC, minorities, and differently-abled students." },
      { q: "When does NSP scholarship application open?", a: "Applications typically open from August to November each year. Check scholarships.gov.in for the current academic year dates." },
      { q: "How do I renew my NSP scholarship?", a: "Login to scholarships.gov.in with your registration ID, select Renewal Application, update your details, and submit a fresh application each year." },
    ],
  },
  {
    slug: "pm-matru-vandana-yojana",
    title: "Pradhan Mantri Matru Vandana Yojana (PMMVY) 2025",
    shortTitle: "PM Matru Vandana",
    description: "PMMVY provides Rs.5,000 cash incentive to pregnant and lactating women for the first living child to partially compensate for wage loss and encourage institutional delivery and proper nutrition.",
    benefit: "Rs.5,000 cash benefit for first child; Rs.6,000 for second child if girl",
    category: "women",
    eligibility: ["All pregnant and lactating women for first living child", "Second child benefit if baby is a girl", "Registered at Anganwadi or health facility"],
    documents: ["Aadhaar Card", "MCP card (Mother and Child Protection card)", "Bank passbook", "Marriage certificate"],
    applyLink: "https://pmmvy.wcd.gov.in",
    launchYear: 2017,
    keywords: ["pmmvy apply online", "matru vandana yojana status", "pm matru vandana Rs.5000", "maternity benefit scheme india"],
    isPopular: false,
    faqs: [
      { q: "How is PMMVY money disbursed?", a: "For the first child: Rs.3,000 after registering pregnancy, Rs.2,000 after one ante-natal check-up. For second child if girl: Rs.6,000 after birth registration." },
      { q: "Can working women apply for PMMVY?", a: "Yes, but those receiving maternity benefits under other government schemes are not eligible. Formal sector employees covered under ESIC or government service are excluded." },
    ],
  },
  {
    slug: "agniveer-scheme",
    title: "Agniveer Scheme — Short-Term Defence Service 2025",
    shortTitle: "Agniveer Scheme",
    description: "Agnipath scheme recruits youth aged 17.5 to 23 years for 4-year service in the Indian Army, Navy, or Air Force as Agniveers, with a Rs.11.71 lakh Seva Nidhi package on completion.",
    benefit: "Rs.30,000 to Rs.40,000/month salary + Rs.11.71 lakh Seva Nidhi after 4 years",
    category: "employment",
    eligibility: ["Indian citizen aged 17.5 to 21 years (check latest notification)", "10th or 12th pass depending on post", "Medically and physically fit as per service standards"],
    documents: ["Aadhaar Card", "10th or 12th mark sheet and certificate", "Birth certificate", "Character certificate", "Medical fitness certificate"],
    applyLink: "https://joinindianarmy.nic.in",
    launchYear: 2022,
    keywords: ["agniveer apply 2025", "agnipath scheme eligibility", "agniveer salary", "agniveer navy air force army apply"],
    isPopular: true,
    faqs: [
      { q: "What is the Seva Nidhi Package under Agniveer scheme?", a: "On completion of 4 years, Agniveers receive Rs.11.71 lakh as Seva Nidhi which includes their monthly contribution plus the government matching contribution with interest." },
      { q: "What percentage of Agniveers are retained permanently?", a: "Up to 25% of Agniveers are eligible to be enrolled as regular cadre in the armed forces based on merit, medical fitness, and performance." },
    ],
  },
];

// ---- State-specific schemes ----

export const maharashtraSchemes: Scheme[] = [
  {
    slug: "ladki-bahin-yojana",
    title: "Mukhyamantri Ladki Bahin Yojana 2025 Maharashtra",
    shortTitle: "Ladki Bahin Yojana",
    description: "Maharashtra government provides Rs.1,500 per month financial assistance directly to eligible women beneficiaries to improve their economic independence.",
    benefit: "Rs.1,500/month direct bank transfer to women",
    category: "women",
    eligibility: ["Maharashtra resident woman", "Age 21 to 65 years", "Annual family income up to Rs.2.5 lakh", "Domicile certificate holder"],
    documents: ["Aadhaar Card", "Domicile Certificate", "Bank Passbook", "Income Certificate", "Age proof"],
    applyLink: "https://namo-shetkari-yojana.maharashtra.gov.in",
    launchYear: 2024,
    keywords: ["ladki bahin yojana apply", "ladki bahin yojana 1500", "ladki bahin eligibility", "maharashtra women scheme 2024"],
    isPopular: true,
    faqs: [
      { q: "What is Mukhyamantri Ladki Bahin Yojana?", a: "It is a Maharashtra state scheme providing Rs.1,500 per month financial assistance to eligible women aged 21-65 with annual family income below Rs.2.5 lakh." },
      { q: "How to apply for Ladki Bahin Yojana?", a: "Apply through the Aaple Sarkar portal or at any Seva Kendra with your Aadhaar, domicile certificate, and bank details." },
    ],
  },
  {
    slug: "namo-shetkari-yojana",
    title: "Namo Shetkari Maha Samman Nidhi Yojana Maharashtra",
    shortTitle: "Namo Shetkari Yojana",
    description: "Maharashtra own farmer income support scheme providing Rs.6,000/year in addition to PM-KISAN, effectively doubling farmer income support to Rs.12,000/year.",
    benefit: "Rs.6,000/year extra on top of PM-KISAN (total Rs.12,000/year)",
    category: "agriculture",
    eligibility: ["Maharashtra resident farmer", "Registered with PM-KISAN", "Valid 7/12 land record"],
    documents: ["7/12 Extract", "Aadhaar Card", "Bank Passbook", "PM-KISAN registration number"],
    applyLink: "https://namo-shetkari-yojana.maharashtra.gov.in",
    launchYear: 2023,
    keywords: ["namo shetkari yojana apply", "namo shetkari status", "maharashtra farmer scheme 2024", "namo shetkari installment"],
    isPopular: true,
    faqs: [
      { q: "Who is eligible for Namo Shetkari Yojana?", a: "Any farmer registered in Maharashtra who is also a PM-KISAN beneficiary can receive the additional Rs.6,000/year." },
    ],
  },
];

export const uttarPradeshSchemes: Scheme[] = [
  {
    slug: "kanya-sumangala-yojana",
    title: "Mukhyamantri Kanya Sumangala Yojana 2025 UP",
    shortTitle: "Kanya Sumangala Yojana",
    description: "Uttar Pradesh government provides financial support of Rs.25,000 to girl children in six stages from birth to graduation to promote girl child welfare and education.",
    benefit: "Rs.25,000 total in 6 instalments from birth to graduation",
    category: "women",
    eligibility: ["UP resident girl child", "Annual family income up to Rs.3 lakh", "Family with max 2 children", "Institutional delivery required for birth instalment"],
    documents: ["Aadhaar Card", "Birth certificate", "Income certificate", "Bank passbook", "School enrollment proof"],
    applyLink: "https://mksy.up.gov.in",
    launchYear: 2019,
    keywords: ["kanya sumangala yojana apply", "kanya sumangala up 25000", "kanya sumangala eligibility", "up girl child scheme"],
    isPopular: true,
    faqs: [
      { q: "What are the 6 stages of Kanya Sumangala benefit?", a: "Rs.2,000 at birth, Rs.1,000 at 1-year immunisation, Rs.2,000 at Class 1 admission, Rs.2,000 at Class 6 admission, Rs.3,000 at Class 9 admission, and Rs.5,000 at Class 12 or graduation." },
      { q: "How to apply for Kanya Sumangala Yojana online?", a: "Apply at mksy.up.gov.in with Aadhaar, bank details, and income certificate. You can also apply offline at the Child Development and Pushti Poshan Officer office." },
    ],
  },
  {
    slug: "up-free-laptop-yojana",
    title: "UP Free Laptop Yojana 2025",
    shortTitle: "UP Free Laptop Yojana",
    description: "Uttar Pradesh government distributes free laptops and tablets to meritorious students who passed Class 10 and Class 12 from UP Board to promote digital education.",
    benefit: "Free laptop or tablet for Class 10 and 12 UP Board toppers",
    category: "education",
    eligibility: ["UP Board Class 10 or 12 student", "Minimum 65% marks in board exam", "UP domicile holder", "Studying in government school"],
    documents: ["Aadhaar Card", "Board mark sheet", "Domicile certificate", "School enrollment proof"],
    applyLink: "https://upcmo.up.nic.in",
    launchYear: 2021,
    keywords: ["up free laptop yojana 2025 apply", "up laptop yojana eligibility", "up board free laptop", "up tablet scheme"],
    isPopular: true,
    faqs: [
      { q: "Who gets free laptops under UP Free Laptop Yojana?", a: "Students from UP Board who scored 65% or more in Class 10 and Class 12 exams and are residents of Uttar Pradesh." },
    ],
  },
];

export const rajasthanSchemes: Scheme[] = [
  {
    slug: "chiranjeevi-health-insurance",
    title: "Mukhyamantri Chiranjeevi Swasthya Bima Yojana 2025",
    shortTitle: "Chiranjeevi Health Insurance",
    description: "Rajasthan flagship health insurance scheme provides cashless treatment coverage of Rs.25 lakh per family per year at empanelled government and private hospitals across Rajasthan.",
    benefit: "Rs.25 lakh cashless health insurance per family per year",
    category: "health",
    eligibility: ["All Rajasthan resident families", "BPL, NFSA, SMF families get it free", "Others can enrol for Rs.850/year premium"],
    documents: ["Jan Aadhaar Card", "Aadhaar Card", "Premium payment receipt for non-free category"],
    applyLink: "https://chiranjeevi.rajasthan.gov.in",
    launchYear: 2021,
    keywords: ["chiranjeevi yojana rajasthan apply", "chiranjeevi health scheme rajasthan", "rajasthan health insurance 25 lakh", "chiranjeevi hospital list"],
    isPopular: true,
    faqs: [
      { q: "Who gets free Chiranjeevi insurance?", a: "BPL families, NFSA food security card holders, small and marginal farmers, and contractual workers. All other Rajasthan families can join for Rs.850/year." },
      { q: "How to register for Chiranjeevi Yojana?", a: "Register online at chiranjeevi.rajasthan.gov.in using your Jan Aadhaar card, or visit your nearest e-Mitra kiosk." },
    ],
  },
  {
    slug: "palanhar-yojana-rajasthan",
    title: "Palanhar Yojana Rajasthan 2025 — Orphan Child Support",
    shortTitle: "Palanhar Yojana",
    description: "Rajasthan Palanhar Yojana provides monthly financial assistance to families who raise orphaned or destitute children to ensure their welfare, education, and nutrition.",
    benefit: "Rs.1,500/month for children up to 5 years; Rs.2,500/month for age 6 to 18",
    category: "women",
    eligibility: ["Orphaned or destitute children", "Children of widows, disabled, or imprisoned parents", "Child must be enrolled in Anganwadi under 6 or school from 6 to 18", "Annual family income up to Rs.1.20 lakh"],
    documents: ["Aadhaar Card", "Child birth certificate", "Parent death or disability certificate", "School or Anganwadi enrollment proof", "Income certificate"],
    applyLink: "https://sje.rajasthan.gov.in",
    launchYear: 2005,
    keywords: ["palanhar yojana rajasthan apply", "palanhar yojana payment status", "palanhar scheme eligibility", "orphan scheme rajasthan"],
    isPopular: false,
    faqs: [
      { q: "Who qualifies as a Palanhar (caretaker)?", a: "Any relative, neighbour, or family member willing to take responsibility for an eligible orphaned or destitute child education and welfare." },
    ],
  },
];

export const gujaratSchemes: Scheme[] = [
  {
    slug: "kisan-suryoday-yojana",
    title: "Kisan Suryoday Yojana Gujarat 2025 — Daytime Electricity",
    shortTitle: "Kisan Suryoday Yojana",
    description: "Gujarat Kisan Suryoday Yojana provides three-phase electricity supply to farmers during daytime (5 AM to 9 PM) for irrigation, eliminating the need for midnight farming operations.",
    benefit: "Daytime 3-phase electricity for irrigation from 5 AM to 9 PM",
    category: "agriculture",
    eligibility: ["Gujarat farmer with agricultural land connection", "Currently receiving night-time supply", "Registered with DGVCL, MGVCL, PGVCL, or UGVCL"],
    documents: ["Electricity connection details", "Land records", "Aadhaar Card"],
    applyLink: "https://agri.gujarat.gov.in",
    launchYear: 2020,
    keywords: ["kisan suryoday yojana gujarat", "gujarat farmer daytime electricity", "suryoday yojana apply", "gujarat agricultural electricity scheme"],
    isPopular: false,
    faqs: [
      { q: "What hours does Kisan Suryoday Yojana provide electricity?", a: "Farmers receive three-phase electricity from 5 AM to 9 PM (16 hours) for their tube wells and pump sets under this scheme." },
    ],
  },
  {
    slug: "mukhyamantri-mahila-utkarsh-yojana",
    title: "Mukhyamantri Mahila Utkarsh Yojana Gujarat 2025",
    shortTitle: "Mahila Utkarsh Yojana",
    description: "Gujarat government provides interest-free loans of Rs.1 lakh to women self-help groups (10 or more members) to help them start income-generating activities and achieve financial independence.",
    benefit: "Interest-free Rs.1 lakh loan to each women SHG member",
    category: "women",
    eligibility: ["Gujarat resident woman", "SHG with minimum 10 members", "Urban or rural area", "Not currently a defaulter"],
    documents: ["Aadhaar Card", "SHG registration certificate", "Bank passbook", "Address proof"],
    applyLink: "https://mmuy.gujarat.gov.in",
    launchYear: 2020,
    keywords: ["mahila utkarsh yojana gujarat apply", "gujarat women shg loan", "mmuy gujarat scheme", "interest free loan women gujarat"],
    isPopular: false,
    faqs: [
      { q: "How much loan do women SHG members get under MMUY?", a: "Each SHG member gets Rs.1 lakh interest-free loan, so a 10-member group collectively receives Rs.10 lakh." },
    ],
  },
];

export const karnatakaSchemes: Scheme[] = [
  {
    slug: "gruha-jyothi-yojana",
    title: "Gruha Jyothi Yojana Karnataka 2025 — 200 Units Free",
    shortTitle: "Gruha Jyothi Yojana",
    description: "Karnataka government provides 200 units of free electricity per month to domestic consumers under the Gruha Jyothi guarantee scheme, covering most middle-class household usage.",
    benefit: "200 units free electricity per month for domestic consumers",
    category: "infrastructure",
    eligibility: ["Karnataka domestic electricity consumer", "Single domestic connection per household", "No commercial connection in the same premises"],
    documents: ["Electricity consumer number", "Aadhaar Card", "Self-declaration of residential use"],
    applyLink: "https://gruha.karnataka.gov.in",
    launchYear: 2023,
    keywords: ["gruha jyothi yojana karnataka", "200 units free electricity karnataka", "karnataka bijli scheme", "gruha jyothi apply"],
    isPopular: true,
    faqs: [
      { q: "What if I use more than 200 units under Gruha Jyothi?", a: "If consumption exceeds 200 units, the first 200 units are free and the remaining are billed at applicable rates. The excess bill must be paid by the consumer." },
    ],
  },
  {
    slug: "anna-bhagya-yojana",
    title: "Anna Bhagya Yojana Karnataka 2025 — 10 Kg Free Rice",
    shortTitle: "Anna Bhagya Yojana",
    description: "Karnataka government provides 10 kg of free rice per person per month to BPL and NFSA cardholders under the Anna Bhagya guarantee scheme to ensure food security.",
    benefit: "10 kg free rice per person per month for BPL families",
    category: "health",
    eligibility: ["Karnataka resident BPL or NFSA cardholder", "Listed in National Food Security Act rolls"],
    documents: ["Ration card (NFSA)", "Aadhaar Card"],
    applyLink: "https://ahara.kar.nic.in",
    launchYear: 2023,
    keywords: ["anna bhagya yojana karnataka 2025", "10 kg free rice karnataka", "karnataka ration scheme", "anna bhagya apply"],
    isPopular: true,
    faqs: [
      { q: "How to get Anna Bhagya rice in Karnataka?", a: "Eligible NFSA cardholders collect the free rice from their designated Fair Price Shop (ration shop) each month." },
    ],
  },
];

export const tamilNaduSchemes: Scheme[] = [
  {
    slug: "kalaignar-magalir-urimai-thogai",
    title: "Kalaignar Magalir Urimai Thogai — Rs.1,000/month Women",
    shortTitle: "Magalir Urimai Thogai",
    description: "Tamil Nadu government provides Rs.1,000 per month directly to the bank accounts of the female head of each family to promote women financial autonomy and economic security.",
    benefit: "Rs.1,000/month to female head of household",
    category: "women",
    eligibility: ["Tamil Nadu resident woman", "Female head of household or nominated female member", "Annual family income up to Rs.2.5 lakh", "Not a government employee or income tax payer"],
    documents: ["Aadhaar Card", "Tamil Nadu ration card", "Bank passbook", "Income certificate"],
    applyLink: "https://www.tn.gov.in",
    launchYear: 2023,
    keywords: ["kalaignar magalir urimai thogai apply", "tn women 1000 scheme", "magalir urimai thogai eligibility", "tamil nadu women scheme 2024"],
    isPopular: true,
    faqs: [
      { q: "Who is the female head of household for this scheme?", a: "The eldest woman in the family who holds the family ration card is considered the female head of household for this scheme." },
    ],
  },
  {
    slug: "pudhumai-penn-scheme",
    title: "Pudhumai Penn Scheme Tamil Nadu 2025 — Rs.1,000 for Girls",
    shortTitle: "Pudhumai Penn Scheme",
    description: "Tamil Nadu Pudhumai Penn scheme provides Rs.1,000 per month to girl students studying in government schools from Class 6 to 12 to encourage continuation of education and reduce dropout rates.",
    benefit: "Rs.1,000/month for girl students in Class 6 to 12 government schools",
    category: "education",
    eligibility: ["Girl student studying in Tamil Nadu government school", "Class 6 to 12", "Regular attendance maintained", "Tamil Nadu resident"],
    documents: ["Aadhaar Card", "School enrollment certificate", "Bank passbook in girl name"],
    applyLink: "https://www.tn.gov.in",
    launchYear: 2023,
    keywords: ["pudhumai penn scheme apply", "tn girl student 1000 scheme", "pudhumai penn eligibility", "tamil nadu girl education scheme"],
    isPopular: false,
    faqs: [
      { q: "Can girls in government-aided schools apply for Pudhumai Penn?", a: "Currently the scheme is for students in government schools only. Students in government-aided or private schools are not eligible." },
    ],
  },
];

// Helper to get schemes by state slug
export function getSchemesByState(stateSlug: string): Scheme[] {
  const stateMap: Record<string, Scheme[]> = {
    "maharashtra": maharashtraSchemes,
    "uttar-pradesh": uttarPradeshSchemes,
    "rajasthan": rajasthanSchemes,
    "gujarat": gujaratSchemes,
    "karnataka": karnatakaSchemes,
    "tamil-nadu": tamilNaduSchemes,
  };
  return stateMap[stateSlug] || [];
}

// Categories with metadata
export const categories = [
  { slug: "agriculture", label: "Agriculture", icon: "🌾", color: "#16a34a" },
  { slug: "education", label: "Education", icon: "📚", color: "#2563eb" },
  { slug: "health", label: "Health", icon: "🏥", color: "#dc2626" },
  { slug: "housing", label: "Housing", icon: "🏠", color: "#d97706" },
  { slug: "employment", label: "Employment", icon: "💼", color: "#7c3aed" },
  { slug: "women", label: "Women", icon: "👩", color: "#db2777" },
  { slug: "finance", label: "Finance", icon: "💰", color: "#0891b2" },
  { slug: "infrastructure", label: "Infrastructure", icon: "🏗️", color: "#374151" },
];
